# Generated by Django 5.0.1 on 2024-01-22 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VotingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('candidate_image', models.ImageField(blank=True, null=True, upload_to='candidate_images/')),
                ('bio', models.CharField(max_length=300)),
                ('votes', models.IntegerField(default=0)),
                ('voting_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votingapp.votingcategory')),
            ],
        ),
    ]
