# Generated by Django 5.0.1 on 2024-01-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='votingcategory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
